[green_agent]
agentbeats_id = "019d0bcf-de7f-76d1-b290-c30e65ddbd1f"
env = { }

[[participants]]
agentbeats_id = ""
name = "agent"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}" }

[config]
competition_id = "spaceship-titanic"
